/**
 * Cart Action types
 */

export const GET_USER_ORDER_LIST = "GET_USER_ORDER_LIST";
export const CLEAR_USER_ORDER_LIST = "CLEAR_USER_ORDER_LIST";
export const GET_USER_ORDER_LIST_ERROR = "GET_USER_ORDER_LIST_ERROR";
export const ADD_USER_ORDER = "ADD_USER_ORDER";
export const START_USER_ORDER_LOADING = "START_USER_ORDER_LOADING";
