
// Home screen actions
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR";
export const GET_BANNERS = "GET_BANNERS";
export const GET_BANNERS_ERROR = "GET_BANNERS_ERROR";

