/**
 * Cart Action types
 */

export const GET_USER_CART_LIST = "GET_USER_CART_LIST";
export const GET_USER_CART_ERROR = "GET_USER_CART_LIST_ERROR";
export const START_USER_CART_LOADING = "START_USER_CART_LOADING";
export const STOP_USER_CART_LOADING = "STOP_USER_CART_LOADING";
export const UPDATE_CART_PRODUCT_QTY = "UPDATE_CART_PRODUCT_QTY";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT";
export const CLEAR_CART_LIST = "CLEAR_CART_LIST";
