export const GET_ADDRESS = "GET_ADDRESS";
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const CHANGE_DEFAULT_ADDRESS = "CHANGE_DEFAULT_ADDRESS";
